markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Walter Pinson
production_url : http://walterpinson.com
description: "Thoughts and musings on credit reporting, startups, software, and various sundries by Walter Pinson."
disqus_shortname: walterpinsonblog
analytics: 
gauges: 
author :
  name : Walter Pinson
  github : walterpinson
  twitter : walterpinson
  email: walter@walterpinson.com
